"""
Generate AF_Spring_Campaign_Slide.pptx — 2-slide briefing.
  Slide 1: Goal & approach (spring AF campaign)
  Slide 2: What's possible — the system behind the list
"""
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

OUTPUT = '/Users/antho/Documents/WPI-MW/donors/AF_Spring_Campaign_Slide.pptx'

# ── Colors ────────────────────────────────────────────────────────────────────
NAVY   = RGBColor(0x1A, 0x3A, 0x5C)
TEAL   = RGBColor(0x2A, 0x9E, 0xA0)
WHITE  = RGBColor(0xFF, 0xFF, 0xFF)
LGRAY  = RGBColor(0xF5, 0xF5, 0xF5)
DGRAY  = RGBColor(0x44, 0x44, 0x44)
MGRAY  = RGBColor(0x88, 0x88, 0x88)
GREEN  = RGBColor(0xD5, 0xE8, 0xD4)
BLUE   = RGBColor(0xDA, 0xE8, 0xFC)
AMBER  = RGBColor(0xFF, 0xE6, 0xCC)
GREEN_D  = RGBColor(0x38, 0x76, 0x1D)
BLUE_D   = RGBColor(0x1F, 0x51, 0x7A)
AMBER_D  = RGBColor(0xA0, 0x52, 0x00)
GOLD   = RGBColor(0xE8, 0x92, 0x2A)

def rgb(r,g,b): return RGBColor(r,g,b)

# ── Helpers ───────────────────────────────────────────────────────────────────
def add_rect(slide, left, top, width, height, fill, line=None, line_w=0.5):
    from pptx.util import Pt
    s = slide.shapes.add_shape(1,
        Inches(left), Inches(top), Inches(width), Inches(height))
    s.fill.solid()
    s.fill.fore_color.rgb = fill
    if line:
        s.line.color.rgb = line
        s.line.width = Pt(line_w)
    else:
        s.line.fill.background()
    return s

def textbox(slide, left, top, width, height, text,
            size=11, bold=False, italic=False,
            color=DGRAY, bg=None, align=PP_ALIGN.LEFT, wrap=True, spacing=None):
    tb = slide.shapes.add_textbox(
        Inches(left), Inches(top), Inches(width), Inches(height))
    tf = tb.text_frame
    tf.word_wrap = wrap
    p = tf.paragraphs[0]
    p.alignment = align
    if spacing:
        from pptx.util import Pt as PPt
        p.space_after = PPt(spacing)
    run = p.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.italic = italic
    run.font.color.rgb = color
    if bg:
        tb.fill.solid()
        tb.fill.fore_color.rgb = bg
    return tb

def title_bar(slide, title, subtitle=None):
    add_rect(slide, 0, 0, 13.33, 1.1, NAVY)
    textbox(slide, 0.35, 0.1, 11, 0.55, title,
            size=26, bold=True, color=WHITE)
    if subtitle:
        textbox(slide, 0.35, 0.65, 11, 0.35, subtitle,
                size=11, italic=True, color=rgb(0xAA,0xCC,0xDD))

prs = Presentation()
prs.slide_width  = Inches(13.33)
prs.slide_height = Inches(7.5)


# ═══════════════════════════════════════════════════════════════════════════════
# SLIDE 1 — Goal & Approach
# ═══════════════════════════════════════════════════════════════════════════════
s1 = prs.slides.add_slide(prs.slide_layouts[6])

title_bar(s1,
    'Annual Fund — Spring Campaign',
    'Growing participation through targeted personal outreach')

s1_bullets = [
    ('Goal',
     'Increase Annual Fund revenue and participation this spring by directing '
     'personal outreach to the patrons most likely to give.'),
    ('Look at the data',
     'Four years of Annual Fund history — who gave, how much, and whether '
     'they typically give in spring or fall.'),
    ('Combine with patron behavior',
     'Attendance, ticket spending, and loyalty patterns show how engaged '
     'each patron is with Music Worcester overall.'),
    ('Segment for the right ask',
     'Group prospects by relationship — renewal, reactivation, or first-time — '
     'so every outreach has a specific, relevant message.'),
    ('Result',
     'A focused list of ~200 priority contacts for personal outreach, plus '
     'an extended list for email and letter follow-up.'),
]

tb = s1.shapes.add_textbox(Inches(0.6), Inches(1.4),
                           Inches(12.1), Inches(5.8))
tf = tb.text_frame
tf.word_wrap = True

for i, (head, body) in enumerate(s1_bullets):
    p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
    p.alignment = PP_ALIGN.LEFT
    p.space_after = Pt(16)
    r1 = p.add_run()
    r1.text = f'•  {head}.  '
    r1.font.size = Pt(22)
    r1.font.bold = True
    r1.font.color.rgb = NAVY
    r2 = p.add_run()
    r2.text = body
    r2.font.size = Pt(20)
    r2.font.bold = False
    r2.font.color.rgb = DGRAY


# ═══════════════════════════════════════════════════════════════════════════════
# SLIDE 2 — What's Possible (simple bullets)
# ═══════════════════════════════════════════════════════════════════════════════
s2 = prs.slides.add_slide(prs.slide_layouts[6])

title_bar(s2,
    "What's Possible — Beyond This Campaign",
    'A reusable system, running locally on your machine')

bullets = [
    ('Built today',
     'Donor segmentation, multiple output formats, and this deck — '
     'all generated by the same pipeline.'),
    ('No stale lists, no resolicitations',
     'Re-run after every Salesforce export — recent donors drop off the '
     'call list automatically.'),
    ('Privacy by design',
     'Salesforce data never leaves your laptop. AI writes the scripts; '
     'it never sees your donor data.'),
    ('Coming next: Mailchimp',
     'Push tranche-specific audiences directly to Mailchimp with targeted '
     'merge fields. You approve every send.'),
]

# Single text frame so paragraph spacing flows naturally
tb = s2.shapes.add_textbox(Inches(0.6), Inches(1.6),
                           Inches(12.1), Inches(5.5))
tf = tb.text_frame
tf.word_wrap = True

for i, (head, body) in enumerate(bullets):
    p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
    p.alignment = PP_ALIGN.LEFT
    p.space_after = Pt(18)
    r1 = p.add_run()
    r1.text = f'•  {head}.  '
    r1.font.size = Pt(24)
    r1.font.bold = True
    r1.font.color.rgb = NAVY
    r2 = p.add_run()
    r2.text = body
    r2.font.size = Pt(22)
    r2.font.bold = False
    r2.font.color.rgb = DGRAY

prs.save(OUTPUT)
print(f'✓ Saved: {OUTPUT}')
